# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_clusters_mgmt_v1_addons_addon_id_delete(self):
        """Test case for api_clusters_mgmt_v1_addons_addon_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_addons_addon_id_get(self):
        """Test case for api_clusters_mgmt_v1_addons_addon_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_addons_addon_id_patch(self):
        """Test case for api_clusters_mgmt_v1_addons_addon_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_addons_addon_id_versions_get(self):
        """Test case for api_clusters_mgmt_v1_addons_addon_id_versions_get

        """
        pass

    def test_api_clusters_mgmt_v1_addons_addon_id_versions_post(self):
        """Test case for api_clusters_mgmt_v1_addons_addon_id_versions_post

        """
        pass

    def test_api_clusters_mgmt_v1_addons_addon_id_versions_version_id_delete(self):
        """Test case for api_clusters_mgmt_v1_addons_addon_id_versions_version_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_addons_addon_id_versions_version_id_get(self):
        """Test case for api_clusters_mgmt_v1_addons_addon_id_versions_version_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_addons_addon_id_versions_version_id_patch(self):
        """Test case for api_clusters_mgmt_v1_addons_addon_id_versions_version_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_addons_get(self):
        """Test case for api_clusters_mgmt_v1_addons_get

        """
        pass

    def test_api_clusters_mgmt_v1_addons_post(self):
        """Test case for api_clusters_mgmt_v1_addons_post

        """
        pass

    def test_api_clusters_mgmt_v1_aws_infrastructure_access_roles_aws_infrastructure_access_role_id_get(self):
        """Test case for api_clusters_mgmt_v1_aws_infrastructure_access_roles_aws_infrastructure_access_role_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_aws_infrastructure_access_roles_get(self):
        """Test case for api_clusters_mgmt_v1_aws_infrastructure_access_roles_get

        """
        pass

    def test_api_clusters_mgmt_v1_aws_inquiries_machine_types_post(self):
        """Test case for api_clusters_mgmt_v1_aws_inquiries_machine_types_post

        """
        pass

    def test_api_clusters_mgmt_v1_aws_inquiries_regions_post(self):
        """Test case for api_clusters_mgmt_v1_aws_inquiries_regions_post

        """
        pass

    def test_api_clusters_mgmt_v1_aws_inquiries_sts_credential_requests_get(self):
        """Test case for api_clusters_mgmt_v1_aws_inquiries_sts_credential_requests_get

        """
        pass

    def test_api_clusters_mgmt_v1_aws_inquiries_sts_policies_get(self):
        """Test case for api_clusters_mgmt_v1_aws_inquiries_sts_policies_get

        """
        pass

    def test_api_clusters_mgmt_v1_aws_inquiries_vpcs_post(self):
        """Test case for api_clusters_mgmt_v1_aws_inquiries_vpcs_post

        """
        pass

    def test_api_clusters_mgmt_v1_cloud_providers_cloud_provider_id_available_regions_post(self):
        """Test case for api_clusters_mgmt_v1_cloud_providers_cloud_provider_id_available_regions_post

        """
        pass

    def test_api_clusters_mgmt_v1_cloud_providers_cloud_provider_id_get(self):
        """Test case for api_clusters_mgmt_v1_cloud_providers_cloud_provider_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_cloud_providers_cloud_provider_id_regions_get(self):
        """Test case for api_clusters_mgmt_v1_cloud_providers_cloud_provider_id_regions_get

        """
        pass

    def test_api_clusters_mgmt_v1_cloud_providers_cloud_provider_id_regions_post(self):
        """Test case for api_clusters_mgmt_v1_cloud_providers_cloud_provider_id_regions_post

        """
        pass

    def test_api_clusters_mgmt_v1_cloud_providers_cloud_provider_id_regions_region_id_delete(self):
        """Test case for api_clusters_mgmt_v1_cloud_providers_cloud_provider_id_regions_region_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_cloud_providers_cloud_provider_id_regions_region_id_get(self):
        """Test case for api_clusters_mgmt_v1_cloud_providers_cloud_provider_id_regions_region_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_cloud_providers_cloud_provider_id_regions_region_id_patch(self):
        """Test case for api_clusters_mgmt_v1_cloud_providers_cloud_provider_id_regions_region_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_cloud_providers_get(self):
        """Test case for api_clusters_mgmt_v1_cloud_providers_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_addon_inquiries_addon_inquiry_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_addon_inquiries_addon_inquiry_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_addon_inquiries_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_addon_inquiries_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_addon_upgrade_policies_addon_upgrade_policy_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_addon_upgrade_policies_addon_upgrade_policy_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_addon_upgrade_policies_addon_upgrade_policy_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_addon_upgrade_policies_addon_upgrade_policy_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_addon_upgrade_policies_addon_upgrade_policy_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_addon_upgrade_policies_addon_upgrade_policy_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_addon_upgrade_policies_addon_upgrade_policy_id_state_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_addon_upgrade_policies_addon_upgrade_policy_id_state_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_addon_upgrade_policies_addon_upgrade_policy_id_state_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_addon_upgrade_policies_addon_upgrade_policy_id_state_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_addon_upgrade_policies_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_addon_upgrade_policies_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_addon_upgrade_policies_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_addon_upgrade_policies_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_addons_addoninstallation_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_addons_addoninstallation_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_addons_addoninstallation_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_addons_addoninstallation_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_addons_addoninstallation_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_addons_addoninstallation_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_addons_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_addons_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_addons_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_addons_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_aws_infrastructure_access_role_grants_aws_infrastructure_access_role_grant_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_aws_infrastructure_access_role_grants_aws_infrastructure_access_role_grant_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_aws_infrastructure_access_role_grants_aws_infrastructure_access_role_grant_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_aws_infrastructure_access_role_grants_aws_infrastructure_access_role_grant_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_aws_infrastructure_access_role_grants_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_aws_infrastructure_access_role_grants_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_aws_infrastructure_access_role_grants_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_aws_infrastructure_access_role_grants_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_aws_private_link_configuration_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_aws_private_link_configuration_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_aws_private_link_configuration_principals_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_aws_private_link_configuration_principals_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_aws_private_link_configuration_principals_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_aws_private_link_configuration_principals_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_aws_private_link_configuration_principals_principal_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_aws_private_link_configuration_principals_principal_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_aws_private_link_configuration_principals_principal_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_aws_private_link_configuration_principals_principal_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_clusterdeployment_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_clusterdeployment_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_control_plane_upgrade_policies_control_plane_upgrade_policy_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_control_plane_upgrade_policies_control_plane_upgrade_policy_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_control_plane_upgrade_policies_control_plane_upgrade_policy_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_control_plane_upgrade_policies_control_plane_upgrade_policy_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_control_plane_upgrade_policies_control_plane_upgrade_policy_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_control_plane_upgrade_policies_control_plane_upgrade_policy_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_control_plane_upgrade_policies_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_control_plane_upgrade_policies_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_control_plane_upgrade_policies_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_control_plane_upgrade_policies_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_credentials_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_credentials_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_delete_protection_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_delete_protection_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_delete_protection_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_delete_protection_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_labels_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_labels_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_labels_label_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_labels_label_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_labels_label_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_labels_label_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_labels_label_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_labels_label_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_labels_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_labels_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_manifests_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_manifests_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_manifests_manifest_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_manifests_manifest_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_manifests_manifest_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_manifests_manifest_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_manifests_manifest_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_manifests_manifest_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_manifests_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_manifests_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_syncsets_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_syncsets_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_syncsets_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_syncsets_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_syncsets_syncset_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_syncsets_syncset_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_syncsets_syncset_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_syncsets_syncset_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_syncsets_syncset_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_external_configuration_syncsets_syncset_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_gate_agreements_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_gate_agreements_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_gate_agreements_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_gate_agreements_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_gate_agreements_version_gate_agreement_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_gate_agreements_version_gate_agreement_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_gate_agreements_version_gate_agreement_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_gate_agreements_version_gate_agreement_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_groups_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_groups_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_groups_group_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_groups_group_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_groups_group_id_users_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_groups_group_id_users_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_groups_group_id_users_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_groups_group_id_users_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_groups_group_id_users_user_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_groups_group_id_users_user_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_groups_group_id_users_user_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_groups_group_id_users_user_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_hibernate_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_hibernate_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_hypershift_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_hypershift_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_htpasswd_users_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_htpasswd_users_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_htpasswd_users_htpasswd_user_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_htpasswd_users_htpasswd_user_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_htpasswd_users_htpasswd_user_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_htpasswd_users_htpasswd_user_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_htpasswd_users_htpasswd_user_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_htpasswd_users_htpasswd_user_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_htpasswd_users_import_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_htpasswd_users_import_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_htpasswd_users_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_htpasswd_users_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_identity_provider_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_identity_providers_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_inflight_checks_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_inflight_checks_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_inflight_checks_inflight_check_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_inflight_checks_inflight_check_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_ingresses_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_ingresses_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_ingresses_ingress_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_ingresses_ingress_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_ingresses_ingress_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_ingresses_ingress_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_ingresses_ingress_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_ingresses_ingress_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_ingresses_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_ingresses_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_ingresses_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_ingresses_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_limited_support_reasons_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_limited_support_reasons_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_limited_support_reasons_limited_support_reason_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_limited_support_reasons_limited_support_reason_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_limited_support_reasons_limited_support_reason_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_limited_support_reasons_limited_support_reason_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_limited_support_reasons_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_limited_support_reasons_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_logs_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_logs_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_logs_install_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_logs_install_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_logs_uninstall_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_logs_uninstall_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_machine_pools_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_machine_pools_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_machine_pools_machine_pool_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_machine_pools_machine_pool_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_machine_pools_machine_pool_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_machine_pools_machine_pool_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_machine_pools_machine_pool_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_machine_pools_machine_pool_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_machine_pools_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_machine_pools_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_metric_queries_alerts_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_metric_queries_alerts_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_metric_queries_cluster_operators_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_metric_queries_cluster_operators_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_metric_queries_cpu_total_by_node_roles_os_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_metric_queries_cpu_total_by_node_roles_os_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_metric_queries_nodes_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_metric_queries_nodes_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_metric_queries_socket_total_by_node_roles_os_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_metric_queries_socket_total_by_node_roles_os_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_node_pools_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_node_pools_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_upgrade_policies_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_upgrade_policies_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_upgrade_policies_node_pool_upgrade_policy_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_upgrade_policies_node_pool_upgrade_policy_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_upgrade_policies_node_pool_upgrade_policy_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_upgrade_policies_node_pool_upgrade_policy_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_upgrade_policies_node_pool_upgrade_policy_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_upgrade_policies_node_pool_upgrade_policy_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_upgrade_policies_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_node_pools_node_pool_id_upgrade_policies_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_node_pools_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_node_pools_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_product_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_product_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_provision_shard_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_provision_shard_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_provision_shard_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_provision_shard_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_provision_shard_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_provision_shard_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_resources_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_resources_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_resources_live_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_resources_live_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_resume_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_resume_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_status_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_status_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_sts_operator_roles_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_sts_operator_roles_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_sts_operator_roles_operator_iam_role_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_sts_operator_roles_operator_iam_role_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_sts_operator_roles_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_sts_operator_roles_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_tuning_configs_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_tuning_configs_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_tuning_configs_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_tuning_configs_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_tuning_configs_tuning_config_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_tuning_configs_tuning_config_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_tuning_configs_tuning_config_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_tuning_configs_tuning_config_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_tuning_configs_tuning_config_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_tuning_configs_tuning_config_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_upgrade_policies_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_upgrade_policies_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_upgrade_policies_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_upgrade_policies_post

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_upgrade_policies_upgrade_policy_id_delete(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_upgrade_policies_upgrade_policy_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_upgrade_policies_upgrade_policy_id_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_upgrade_policies_upgrade_policy_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_upgrade_policies_upgrade_policy_id_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_upgrade_policies_upgrade_policy_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_upgrade_policies_upgrade_policy_id_state_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_upgrade_policies_upgrade_policy_id_state_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_cluster_id_upgrade_policies_upgrade_policy_id_state_patch(self):
        """Test case for api_clusters_mgmt_v1_clusters_cluster_id_upgrade_policies_upgrade_policy_id_state_patch

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_get(self):
        """Test case for api_clusters_mgmt_v1_clusters_get

        """
        pass

    def test_api_clusters_mgmt_v1_clusters_post(self):
        """Test case for api_clusters_mgmt_v1_clusters_post

        """
        pass

    def test_api_clusters_mgmt_v1_dns_domains_dns_domain_id_delete(self):
        """Test case for api_clusters_mgmt_v1_dns_domains_dns_domain_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_dns_domains_dns_domain_id_get(self):
        """Test case for api_clusters_mgmt_v1_dns_domains_dns_domain_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_dns_domains_dns_domain_id_patch(self):
        """Test case for api_clusters_mgmt_v1_dns_domains_dns_domain_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_dns_domains_get(self):
        """Test case for api_clusters_mgmt_v1_dns_domains_get

        """
        pass

    def test_api_clusters_mgmt_v1_dns_domains_post(self):
        """Test case for api_clusters_mgmt_v1_dns_domains_post

        """
        pass

    def test_api_clusters_mgmt_v1_environment_get(self):
        """Test case for api_clusters_mgmt_v1_environment_get

        """
        pass

    def test_api_clusters_mgmt_v1_environment_patch(self):
        """Test case for api_clusters_mgmt_v1_environment_patch

        """
        pass

    def test_api_clusters_mgmt_v1_events_post(self):
        """Test case for api_clusters_mgmt_v1_events_post

        """
        pass

    def test_api_clusters_mgmt_v1_flavours_flavour_id_get(self):
        """Test case for api_clusters_mgmt_v1_flavours_flavour_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_flavours_flavour_id_patch(self):
        """Test case for api_clusters_mgmt_v1_flavours_flavour_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_flavours_get(self):
        """Test case for api_clusters_mgmt_v1_flavours_get

        """
        pass

    def test_api_clusters_mgmt_v1_flavours_post(self):
        """Test case for api_clusters_mgmt_v1_flavours_post

        """
        pass

    def test_api_clusters_mgmt_v1_gcp_inquiries_encryption_keys_post(self):
        """Test case for api_clusters_mgmt_v1_gcp_inquiries_encryption_keys_post

        """
        pass

    def test_api_clusters_mgmt_v1_gcp_inquiries_key_rings_post(self):
        """Test case for api_clusters_mgmt_v1_gcp_inquiries_key_rings_post

        """
        pass

    def test_api_clusters_mgmt_v1_gcp_inquiries_regions_post(self):
        """Test case for api_clusters_mgmt_v1_gcp_inquiries_regions_post

        """
        pass

    def test_api_clusters_mgmt_v1_gcp_inquiries_vpcs_post(self):
        """Test case for api_clusters_mgmt_v1_gcp_inquiries_vpcs_post

        """
        pass

    def test_api_clusters_mgmt_v1_get(self):
        """Test case for api_clusters_mgmt_v1_get

        """
        pass

    def test_api_clusters_mgmt_v1_limited_support_reason_templates_get(self):
        """Test case for api_clusters_mgmt_v1_limited_support_reason_templates_get

        """
        pass

    def test_api_clusters_mgmt_v1_limited_support_reason_templates_limited_support_reason_template_id_get(self):
        """Test case for api_clusters_mgmt_v1_limited_support_reason_templates_limited_support_reason_template_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_machine_types_get(self):
        """Test case for api_clusters_mgmt_v1_machine_types_get

        """
        pass

    def test_api_clusters_mgmt_v1_machine_types_machine_type_id_get(self):
        """Test case for api_clusters_mgmt_v1_machine_types_machine_type_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_oidc_configs_get(self):
        """Test case for api_clusters_mgmt_v1_oidc_configs_get

        """
        pass

    def test_api_clusters_mgmt_v1_oidc_configs_oidc_config_id_delete(self):
        """Test case for api_clusters_mgmt_v1_oidc_configs_oidc_config_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_oidc_configs_oidc_config_id_get(self):
        """Test case for api_clusters_mgmt_v1_oidc_configs_oidc_config_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_oidc_configs_oidc_config_id_patch(self):
        """Test case for api_clusters_mgmt_v1_oidc_configs_oidc_config_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_oidc_configs_post(self):
        """Test case for api_clusters_mgmt_v1_oidc_configs_post

        """
        pass

    def test_api_clusters_mgmt_v1_pending_delete_clusters_get(self):
        """Test case for api_clusters_mgmt_v1_pending_delete_clusters_get

        """
        pass

    def test_api_clusters_mgmt_v1_pending_delete_clusters_pending_delete_cluster_id_get(self):
        """Test case for api_clusters_mgmt_v1_pending_delete_clusters_pending_delete_cluster_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_pending_delete_clusters_pending_delete_cluster_id_patch(self):
        """Test case for api_clusters_mgmt_v1_pending_delete_clusters_pending_delete_cluster_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_products_get(self):
        """Test case for api_clusters_mgmt_v1_products_get

        """
        pass

    def test_api_clusters_mgmt_v1_products_product_id_get(self):
        """Test case for api_clusters_mgmt_v1_products_product_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_provision_shards_get(self):
        """Test case for api_clusters_mgmt_v1_provision_shards_get

        """
        pass

    def test_api_clusters_mgmt_v1_provision_shards_post(self):
        """Test case for api_clusters_mgmt_v1_provision_shards_post

        """
        pass

    def test_api_clusters_mgmt_v1_provision_shards_provision_shard_id_delete(self):
        """Test case for api_clusters_mgmt_v1_provision_shards_provision_shard_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_provision_shards_provision_shard_id_get(self):
        """Test case for api_clusters_mgmt_v1_provision_shards_provision_shard_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_provision_shards_provision_shard_id_patch(self):
        """Test case for api_clusters_mgmt_v1_provision_shards_provision_shard_id_patch

        """
        pass

    def test_api_clusters_mgmt_v1_version_gates_get(self):
        """Test case for api_clusters_mgmt_v1_version_gates_get

        """
        pass

    def test_api_clusters_mgmt_v1_version_gates_post(self):
        """Test case for api_clusters_mgmt_v1_version_gates_post

        """
        pass

    def test_api_clusters_mgmt_v1_version_gates_version_gate_id_delete(self):
        """Test case for api_clusters_mgmt_v1_version_gates_version_gate_id_delete

        """
        pass

    def test_api_clusters_mgmt_v1_version_gates_version_gate_id_get(self):
        """Test case for api_clusters_mgmt_v1_version_gates_version_gate_id_get

        """
        pass

    def test_api_clusters_mgmt_v1_versions_get(self):
        """Test case for api_clusters_mgmt_v1_versions_get

        """
        pass

    def test_api_clusters_mgmt_v1_versions_version_id_get(self):
        """Test case for api_clusters_mgmt_v1_versions_version_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
