# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response20020 import InlineResponse20020  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse20020(unittest.TestCase):
    """InlineResponse20020 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20020
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response20020.InlineResponse20020()  # noqa: E501
        if include_optional :
            return InlineResponse20020(
                items = [
                    openapi_client.models.version_gate_agreement.VersionGateAgreement(
                        kind = '0', 
                        id = '0', 
                        href = '0', 
                        agreed_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        version_gate = openapi_client.models.version_gate.VersionGate(
                            kind = '0', 
                            id = '0', 
                            href = '0', 
                            sts_only = True, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            description = '0', 
                            documentation_url = '0', 
                            label = '0', 
                            value = '0', 
                            version_raw_id_prefix = '0', 
                            warning_message = '0', ), )
                    ], 
                page = 56, 
                size = 56, 
                total = 56
            )
        else :
            return InlineResponse20020(
        )

    def testInlineResponse20020(self):
        """Test InlineResponse20020"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
