# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.ldap_identity_provider import LDAPIdentityProvider  # noqa: E501
from openapi_client.rest import ApiException

class TestLDAPIdentityProvider(unittest.TestCase):
    """LDAPIdentityProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LDAPIdentityProvider
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.ldap_identity_provider.LDAPIdentityProvider()  # noqa: E501
        if include_optional :
            return LDAPIdentityProvider(
                ca = '0', 
                url = '0', 
                attributes = openapi_client.models.ldap_attributes.LDAPAttributes(
                    id = [
                        '0'
                        ], 
                    email = [
                        '0'
                        ], 
                    name = [
                        '0'
                        ], 
                    preferred_username = [
                        '0'
                        ], ), 
                bind_dn = '0', 
                bind_password = '0', 
                insecure = True
            )
        else :
            return LDAPIdentityProvider(
        )

    def testLDAPIdentityProvider(self):
        """Test LDAPIdentityProvider"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
