# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.sts_operator import STSOperator  # noqa: E501
from openapi_client.rest import ApiException

class TestSTSOperator(unittest.TestCase):
    """STSOperator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test STSOperator
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.sts_operator.STSOperator()  # noqa: E501
        if include_optional :
            return STSOperator(
                max_version = '0', 
                min_version = '0', 
                name = '0', 
                namespace = '0', 
                service_accounts = [
                    '0'
                    ]
            )
        else :
            return STSOperator(
        )

    def testSTSOperator(self):
        """Test STSOperator"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
