# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ocm_client
from ocm_client.models.inline_response20049 import InlineResponse20049  # noqa: E501
from ocm_client.rest import ApiException

class TestInlineResponse20049(unittest.TestCase):
    """InlineResponse20049 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20049
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ocm_client.models.inline_response20049.InlineResponse20049()  # noqa: E501
        if include_optional :
            return InlineResponse20049(
                items = [
                    ocm_client.models.trusted_ip.TrustedIp(
                        kind = '0', 
                        id = '0', 
                        href = '0', 
                        enabled = True, )
                    ], 
                page = 56, 
                size = 56, 
                total = 56
            )
        else :
            return InlineResponse20049(
        )

    def testInlineResponse20049(self):
        """Test InlineResponse20049"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
