# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.operator_iam_role import OperatorIAMRole  # noqa: E501
from openapi_client.rest import ApiException

class TestOperatorIAMRole(unittest.TestCase):
    """OperatorIAMRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OperatorIAMRole
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.operator_iam_role.OperatorIAMRole()  # noqa: E501
        if include_optional :
            return OperatorIAMRole(
                id = '0', 
                name = '0', 
                namespace = '0', 
                role_arn = '0', 
                service_account = '0'
            )
        else :
            return OperatorIAMRole(
        )

    def testOperatorIAMRole(self):
        """Test OperatorIAMRole"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
