# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response20040 import InlineResponse20040  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse20040(unittest.TestCase):
    """InlineResponse20040 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20040
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response20040.InlineResponse20040()  # noqa: E501
        if include_optional :
            return InlineResponse20040(
                items = [
                    openapi_client.models.limited_support_reason_template.LimitedSupportReasonTemplate(
                        kind = '0', 
                        id = '0', 
                        href = '0', 
                        details = '0', 
                        summary = '0', )
                    ], 
                page = 56, 
                size = 56, 
                total = 56
            )
        else :
            return InlineResponse20040(
        )

    def testInlineResponse20040(self):
        """Test InlineResponse20040"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
