# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ocm_client.configuration import Configuration


class AddOnSecretPropagation(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'destination_secret': 'str',
        'enabled': 'bool',
        'source_secret': 'str'
    }

    attribute_map = {
        'id': 'id',
        'destination_secret': 'destination_secret',
        'enabled': 'enabled',
        'source_secret': 'source_secret'
    }

    def __init__(self, id=None, destination_secret=None, enabled=None, source_secret=None, local_vars_configuration=None):  # noqa: E501
        """AddOnSecretPropagation - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._destination_secret = None
        self._enabled = None
        self._source_secret = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if destination_secret is not None:
            self.destination_secret = destination_secret
        if enabled is not None:
            self.enabled = enabled
        if source_secret is not None:
            self.source_secret = source_secret

    @property
    def id(self):
        """Gets the id of this AddOnSecretPropagation.  # noqa: E501

        ID of the secret propagation  # noqa: E501

        :return: The id of this AddOnSecretPropagation.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AddOnSecretPropagation.

        ID of the secret propagation  # noqa: E501

        :param id: The id of this AddOnSecretPropagation.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def destination_secret(self):
        """Gets the destination_secret of this AddOnSecretPropagation.  # noqa: E501

        DestinationSecret is location of the secret to be added  # noqa: E501

        :return: The destination_secret of this AddOnSecretPropagation.  # noqa: E501
        :rtype: str
        """
        return self._destination_secret

    @destination_secret.setter
    def destination_secret(self, destination_secret):
        """Sets the destination_secret of this AddOnSecretPropagation.

        DestinationSecret is location of the secret to be added  # noqa: E501

        :param destination_secret: The destination_secret of this AddOnSecretPropagation.  # noqa: E501
        :type: str
        """

        self._destination_secret = destination_secret

    @property
    def enabled(self):
        """Gets the enabled of this AddOnSecretPropagation.  # noqa: E501

        Indicates is this secret propagation is enabled for the addon  # noqa: E501

        :return: The enabled of this AddOnSecretPropagation.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this AddOnSecretPropagation.

        Indicates is this secret propagation is enabled for the addon  # noqa: E501

        :param enabled: The enabled of this AddOnSecretPropagation.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def source_secret(self):
        """Gets the source_secret of this AddOnSecretPropagation.  # noqa: E501

        SourceSecret is location of the source secret  # noqa: E501

        :return: The source_secret of this AddOnSecretPropagation.  # noqa: E501
        :rtype: str
        """
        return self._source_secret

    @source_secret.setter
    def source_secret(self, source_secret):
        """Sets the source_secret of this AddOnSecretPropagation.

        SourceSecret is location of the source secret  # noqa: E501

        :param source_secret: The source_secret of this AddOnSecretPropagation.  # noqa: E501
        :type: str
        """

        self._source_secret = source_secret

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddOnSecretPropagation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AddOnSecretPropagation):
            return True

        return self.to_dict() != other.to_dict()
