# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ocm_client.configuration import Configuration


class AWSNodePool(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'kind': 'str',
        'id': 'str',
        'href': 'str',
        'instance_profile': 'str',
        'instance_type': 'str',
        'tags': 'dict(str, str)'
    }

    attribute_map = {
        'kind': 'kind',
        'id': 'id',
        'href': 'href',
        'instance_profile': 'instance_profile',
        'instance_type': 'instance_type',
        'tags': 'tags'
    }

    def __init__(self, kind=None, id=None, href=None, instance_profile=None, instance_type=None, tags=None, local_vars_configuration=None):  # noqa: E501
        """AWSNodePool - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._kind = None
        self._id = None
        self._href = None
        self._instance_profile = None
        self._instance_type = None
        self._tags = None
        self.discriminator = None

        if kind is not None:
            self.kind = kind
        if id is not None:
            self.id = id
        if href is not None:
            self.href = href
        if instance_profile is not None:
            self.instance_profile = instance_profile
        if instance_type is not None:
            self.instance_type = instance_type
        if tags is not None:
            self.tags = tags

    @property
    def kind(self):
        """Gets the kind of this AWSNodePool.  # noqa: E501

        Indicates the type of this object. Will be 'AWSNodePool' if this is a complete object or 'AWSNodePoolLink' if it is just a link.  # noqa: E501

        :return: The kind of this AWSNodePool.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this AWSNodePool.

        Indicates the type of this object. Will be 'AWSNodePool' if this is a complete object or 'AWSNodePoolLink' if it is just a link.  # noqa: E501

        :param kind: The kind of this AWSNodePool.  # noqa: E501
        :type: str
        """

        self._kind = kind

    @property
    def id(self):
        """Gets the id of this AWSNodePool.  # noqa: E501

        Unique identifier of the object.  # noqa: E501

        :return: The id of this AWSNodePool.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AWSNodePool.

        Unique identifier of the object.  # noqa: E501

        :param id: The id of this AWSNodePool.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def href(self):
        """Gets the href of this AWSNodePool.  # noqa: E501

        Self link.  # noqa: E501

        :return: The href of this AWSNodePool.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this AWSNodePool.

        Self link.  # noqa: E501

        :param href: The href of this AWSNodePool.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def instance_profile(self):
        """Gets the instance_profile of this AWSNodePool.  # noqa: E501

        InstanceProfile is the AWS EC2 instance profile, which is a container for an IAM role that the EC2 instance uses.  # noqa: E501

        :return: The instance_profile of this AWSNodePool.  # noqa: E501
        :rtype: str
        """
        return self._instance_profile

    @instance_profile.setter
    def instance_profile(self, instance_profile):
        """Sets the instance_profile of this AWSNodePool.

        InstanceProfile is the AWS EC2 instance profile, which is a container for an IAM role that the EC2 instance uses.  # noqa: E501

        :param instance_profile: The instance_profile of this AWSNodePool.  # noqa: E501
        :type: str
        """

        self._instance_profile = instance_profile

    @property
    def instance_type(self):
        """Gets the instance_type of this AWSNodePool.  # noqa: E501

        InstanceType is an ec2 instance type for node instances (e.g. m5.large).  # noqa: E501

        :return: The instance_type of this AWSNodePool.  # noqa: E501
        :rtype: str
        """
        return self._instance_type

    @instance_type.setter
    def instance_type(self, instance_type):
        """Sets the instance_type of this AWSNodePool.

        InstanceType is an ec2 instance type for node instances (e.g. m5.large).  # noqa: E501

        :param instance_type: The instance_type of this AWSNodePool.  # noqa: E501
        :type: str
        """

        self._instance_type = instance_type

    @property
    def tags(self):
        """Gets the tags of this AWSNodePool.  # noqa: E501

        Optional keys and values that the installer will add as tags to all AWS resources it creates  # noqa: E501

        :return: The tags of this AWSNodePool.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this AWSNodePool.

        Optional keys and values that the installer will add as tags to all AWS resources it creates  # noqa: E501

        :param tags: The tags of this AWSNodePool.  # noqa: E501
        :type: dict(str, str)
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AWSNodePool):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AWSNodePool):
            return True

        return self.to_dict() != other.to_dict()
