# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ocm_client.configuration import Configuration


class ClusterResources(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'kind': 'str',
        'id': 'str',
        'href': 'str',
        'cluster_id': 'str',
        'creation_timestamp': 'datetime',
        'resources': 'dict(str, str)'
    }

    attribute_map = {
        'kind': 'kind',
        'id': 'id',
        'href': 'href',
        'cluster_id': 'cluster_id',
        'creation_timestamp': 'creation_timestamp',
        'resources': 'resources'
    }

    def __init__(self, kind=None, id=None, href=None, cluster_id=None, creation_timestamp=None, resources=None, local_vars_configuration=None):  # noqa: E501
        """ClusterResources - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._kind = None
        self._id = None
        self._href = None
        self._cluster_id = None
        self._creation_timestamp = None
        self._resources = None
        self.discriminator = None

        if kind is not None:
            self.kind = kind
        if id is not None:
            self.id = id
        if href is not None:
            self.href = href
        if cluster_id is not None:
            self.cluster_id = cluster_id
        if creation_timestamp is not None:
            self.creation_timestamp = creation_timestamp
        if resources is not None:
            self.resources = resources

    @property
    def kind(self):
        """Gets the kind of this ClusterResources.  # noqa: E501

        Indicates the type of this object. Will be 'ClusterResources' if this is a complete object or 'ClusterResourcesLink' if it is just a link.  # noqa: E501

        :return: The kind of this ClusterResources.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this ClusterResources.

        Indicates the type of this object. Will be 'ClusterResources' if this is a complete object or 'ClusterResourcesLink' if it is just a link.  # noqa: E501

        :param kind: The kind of this ClusterResources.  # noqa: E501
        :type: str
        """

        self._kind = kind

    @property
    def id(self):
        """Gets the id of this ClusterResources.  # noqa: E501

        Unique identifier of the object.  # noqa: E501

        :return: The id of this ClusterResources.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ClusterResources.

        Unique identifier of the object.  # noqa: E501

        :param id: The id of this ClusterResources.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def href(self):
        """Gets the href of this ClusterResources.  # noqa: E501

        Self link.  # noqa: E501

        :return: The href of this ClusterResources.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this ClusterResources.

        Self link.  # noqa: E501

        :param href: The href of this ClusterResources.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def cluster_id(self):
        """Gets the cluster_id of this ClusterResources.  # noqa: E501

        Cluster ID for the fetched resources  # noqa: E501

        :return: The cluster_id of this ClusterResources.  # noqa: E501
        :rtype: str
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this ClusterResources.

        Cluster ID for the fetched resources  # noqa: E501

        :param cluster_id: The cluster_id of this ClusterResources.  # noqa: E501
        :type: str
        """

        self._cluster_id = cluster_id

    @property
    def creation_timestamp(self):
        """Gets the creation_timestamp of this ClusterResources.  # noqa: E501

        Date and time when the resources were fetched.  # noqa: E501

        :return: The creation_timestamp of this ClusterResources.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_timestamp

    @creation_timestamp.setter
    def creation_timestamp(self, creation_timestamp):
        """Sets the creation_timestamp of this ClusterResources.

        Date and time when the resources were fetched.  # noqa: E501

        :param creation_timestamp: The creation_timestamp of this ClusterResources.  # noqa: E501
        :type: datetime
        """

        self._creation_timestamp = creation_timestamp

    @property
    def resources(self):
        """Gets the resources of this ClusterResources.  # noqa: E501

        Returned map of cluster resources fetched.  # noqa: E501

        :return: The resources of this ClusterResources.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this ClusterResources.

        Returned map of cluster resources fetched.  # noqa: E501

        :param resources: The resources of this ClusterResources.  # noqa: E501
        :type: dict(str, str)
        """

        self._resources = resources

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClusterResources):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ClusterResources):
            return True

        return self.to_dict() != other.to_dict()
