# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ocm_client.configuration import Configuration


class CredentialRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'namespace': 'str',
        'policy_permissions': 'list[str]',
        'service_account': 'str'
    }

    attribute_map = {
        'name': 'name',
        'namespace': 'namespace',
        'policy_permissions': 'policy_permissions',
        'service_account': 'service_account'
    }

    def __init__(self, name=None, namespace=None, policy_permissions=None, service_account=None, local_vars_configuration=None):  # noqa: E501
        """CredentialRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._namespace = None
        self._policy_permissions = None
        self._service_account = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if namespace is not None:
            self.namespace = namespace
        if policy_permissions is not None:
            self.policy_permissions = policy_permissions
        if service_account is not None:
            self.service_account = service_account

    @property
    def name(self):
        """Gets the name of this CredentialRequest.  # noqa: E501

        Name of the credentials secret used to access cloud resources  # noqa: E501

        :return: The name of this CredentialRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CredentialRequest.

        Name of the credentials secret used to access cloud resources  # noqa: E501

        :param name: The name of this CredentialRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def namespace(self):
        """Gets the namespace of this CredentialRequest.  # noqa: E501

        Namespace where the credentials secret lives in the cluster  # noqa: E501

        :return: The namespace of this CredentialRequest.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this CredentialRequest.

        Namespace where the credentials secret lives in the cluster  # noqa: E501

        :param namespace: The namespace of this CredentialRequest.  # noqa: E501
        :type: str
        """

        self._namespace = namespace

    @property
    def policy_permissions(self):
        """Gets the policy_permissions of this CredentialRequest.  # noqa: E501

        List of policy permissions needed to access cloud resources  # noqa: E501

        :return: The policy_permissions of this CredentialRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._policy_permissions

    @policy_permissions.setter
    def policy_permissions(self, policy_permissions):
        """Sets the policy_permissions of this CredentialRequest.

        List of policy permissions needed to access cloud resources  # noqa: E501

        :param policy_permissions: The policy_permissions of this CredentialRequest.  # noqa: E501
        :type: list[str]
        """

        self._policy_permissions = policy_permissions

    @property
    def service_account(self):
        """Gets the service_account of this CredentialRequest.  # noqa: E501

        Service account name to use when authenticating  # noqa: E501

        :return: The service_account of this CredentialRequest.  # noqa: E501
        :rtype: str
        """
        return self._service_account

    @service_account.setter
    def service_account(self, service_account):
        """Sets the service_account of this CredentialRequest.

        Service account name to use when authenticating  # noqa: E501

        :param service_account: The service_account of this CredentialRequest.  # noqa: E501
        :type: str
        """

        self._service_account = service_account

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CredentialRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CredentialRequest):
            return True

        return self.to_dict() != other.to_dict()
