# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ocm_client.configuration import Configuration


class GcpSecurity(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'secure_boot': 'bool'
    }

    attribute_map = {
        'secure_boot': 'secure_boot'
    }

    def __init__(self, secure_boot=None, local_vars_configuration=None):  # noqa: E501
        """GcpSecurity - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._secure_boot = None
        self.discriminator = None

        if secure_boot is not None:
            self.secure_boot = secure_boot

    @property
    def secure_boot(self):
        """Gets the secure_boot of this GcpSecurity.  # noqa: E501

        Determines if Shielded VM feature \"Secure Boot\" should be set for the nodes of the cluster.  # noqa: E501

        :return: The secure_boot of this GcpSecurity.  # noqa: E501
        :rtype: bool
        """
        return self._secure_boot

    @secure_boot.setter
    def secure_boot(self, secure_boot):
        """Sets the secure_boot of this GcpSecurity.

        Determines if Shielded VM feature \"Secure Boot\" should be set for the nodes of the cluster.  # noqa: E501

        :param secure_boot: The secure_boot of this GcpSecurity.  # noqa: E501
        :type: bool
        """

        self._secure_boot = secure_boot

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GcpSecurity):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GcpSecurity):
            return True

        return self.to_dict() != other.to_dict()
