# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ocm_client.configuration import Configuration


class HTPasswdUser(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'hashed_password': 'str',
        'password': 'str',
        'username': 'str'
    }

    attribute_map = {
        'id': 'id',
        'hashed_password': 'hashed_password',
        'password': 'password',
        'username': 'username'
    }

    def __init__(self, id=None, hashed_password=None, password=None, username=None, local_vars_configuration=None):  # noqa: E501
        """HTPasswdUser - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._hashed_password = None
        self._password = None
        self._username = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if hashed_password is not None:
            self.hashed_password = hashed_password
        if password is not None:
            self.password = password
        if username is not None:
            self.username = username

    @property
    def id(self):
        """Gets the id of this HTPasswdUser.  # noqa: E501

        ID for a secondary user in the _HTPasswd_ data file.  # noqa: E501

        :return: The id of this HTPasswdUser.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this HTPasswdUser.

        ID for a secondary user in the _HTPasswd_ data file.  # noqa: E501

        :param id: The id of this HTPasswdUser.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def hashed_password(self):
        """Gets the hashed_password of this HTPasswdUser.  # noqa: E501

        HTPasswd Hashed Password for a user in the _HTPasswd_ data file. The value of this field is set as-is in the _HTPasswd_ data file for the HTPasswd IDP  # noqa: E501

        :return: The hashed_password of this HTPasswdUser.  # noqa: E501
        :rtype: str
        """
        return self._hashed_password

    @hashed_password.setter
    def hashed_password(self, hashed_password):
        """Sets the hashed_password of this HTPasswdUser.

        HTPasswd Hashed Password for a user in the _HTPasswd_ data file. The value of this field is set as-is in the _HTPasswd_ data file for the HTPasswd IDP  # noqa: E501

        :param hashed_password: The hashed_password of this HTPasswdUser.  # noqa: E501
        :type: str
        """

        self._hashed_password = hashed_password

    @property
    def password(self):
        """Gets the password of this HTPasswdUser.  # noqa: E501

        Password in plain-text for a  user in the _HTPasswd_ data file. The value of this field is hashed before setting it in the  _HTPasswd_ data file for the HTPasswd IDP  # noqa: E501

        :return: The password of this HTPasswdUser.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this HTPasswdUser.

        Password in plain-text for a  user in the _HTPasswd_ data file. The value of this field is hashed before setting it in the  _HTPasswd_ data file for the HTPasswd IDP  # noqa: E501

        :param password: The password of this HTPasswdUser.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def username(self):
        """Gets the username of this HTPasswdUser.  # noqa: E501

        Username for a secondary user in the _HTPasswd_ data file.  # noqa: E501

        :return: The username of this HTPasswdUser.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this HTPasswdUser.

        Username for a secondary user in the _HTPasswd_ data file.  # noqa: E501

        :param username: The username of this HTPasswdUser.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HTPasswdUser):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HTPasswdUser):
            return True

        return self.to_dict() != other.to_dict()
