# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ocm_client.configuration import Configuration


class HypershiftConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'enabled': 'bool',
        'management_cluster': 'str'
    }

    attribute_map = {
        'enabled': 'enabled',
        'management_cluster': 'management_cluster'
    }

    def __init__(self, enabled=None, management_cluster=None, local_vars_configuration=None):  # noqa: E501
        """HypershiftConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._enabled = None
        self._management_cluster = None
        self.discriminator = None

        if enabled is not None:
            self.enabled = enabled
        if management_cluster is not None:
            self.management_cluster = management_cluster

    @property
    def enabled(self):
        """Gets the enabled of this HypershiftConfig.  # noqa: E501

        Boolean flag indicating if the cluster should be creating using _Hypershift_.  By default this is `false`.  To enable it the cluster needs to be ROSA cluster and the organization of the user needs to have the `hypershift` capability enabled.  # noqa: E501

        :return: The enabled of this HypershiftConfig.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this HypershiftConfig.

        Boolean flag indicating if the cluster should be creating using _Hypershift_.  By default this is `false`.  To enable it the cluster needs to be ROSA cluster and the organization of the user needs to have the `hypershift` capability enabled.  # noqa: E501

        :param enabled: The enabled of this HypershiftConfig.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def management_cluster(self):
        """Gets the management_cluster of this HypershiftConfig.  # noqa: E501

        Contains the name of the current management cluster for this Hypershift cluster. Empty for non Hypershift clusters.  # noqa: E501

        :return: The management_cluster of this HypershiftConfig.  # noqa: E501
        :rtype: str
        """
        return self._management_cluster

    @management_cluster.setter
    def management_cluster(self, management_cluster):
        """Sets the management_cluster of this HypershiftConfig.

        Contains the name of the current management cluster for this Hypershift cluster. Empty for non Hypershift clusters.  # noqa: E501

        :param management_cluster: The management_cluster of this HypershiftConfig.  # noqa: E501
        :type: str
        """

        self._management_cluster = management_cluster

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HypershiftConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HypershiftConfig):
            return True

        return self.to_dict() != other.to_dict()
