# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ocm_client.configuration import Configuration


class InflightCheck(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'kind': 'str',
        'id': 'str',
        'href': 'str',
        'details': 'object',
        'ended_at': 'datetime',
        'name': 'str',
        'restarts': 'int',
        'started_at': 'datetime',
        'state': 'InflightCheckState'
    }

    attribute_map = {
        'kind': 'kind',
        'id': 'id',
        'href': 'href',
        'details': 'details',
        'ended_at': 'ended_at',
        'name': 'name',
        'restarts': 'restarts',
        'started_at': 'started_at',
        'state': 'state'
    }

    def __init__(self, kind=None, id=None, href=None, details=None, ended_at=None, name=None, restarts=None, started_at=None, state=None, local_vars_configuration=None):  # noqa: E501
        """InflightCheck - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._kind = None
        self._id = None
        self._href = None
        self._details = None
        self._ended_at = None
        self._name = None
        self._restarts = None
        self._started_at = None
        self._state = None
        self.discriminator = None

        if kind is not None:
            self.kind = kind
        if id is not None:
            self.id = id
        if href is not None:
            self.href = href
        if details is not None:
            self.details = details
        if ended_at is not None:
            self.ended_at = ended_at
        if name is not None:
            self.name = name
        if restarts is not None:
            self.restarts = restarts
        if started_at is not None:
            self.started_at = started_at
        if state is not None:
            self.state = state

    @property
    def kind(self):
        """Gets the kind of this InflightCheck.  # noqa: E501

        Indicates the type of this object. Will be 'InflightCheck' if this is a complete object or 'InflightCheckLink' if it is just a link.  # noqa: E501

        :return: The kind of this InflightCheck.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this InflightCheck.

        Indicates the type of this object. Will be 'InflightCheck' if this is a complete object or 'InflightCheckLink' if it is just a link.  # noqa: E501

        :param kind: The kind of this InflightCheck.  # noqa: E501
        :type: str
        """

        self._kind = kind

    @property
    def id(self):
        """Gets the id of this InflightCheck.  # noqa: E501

        Unique identifier of the object.  # noqa: E501

        :return: The id of this InflightCheck.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InflightCheck.

        Unique identifier of the object.  # noqa: E501

        :param id: The id of this InflightCheck.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def href(self):
        """Gets the href of this InflightCheck.  # noqa: E501

        Self link.  # noqa: E501

        :return: The href of this InflightCheck.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this InflightCheck.

        Self link.  # noqa: E501

        :param href: The href of this InflightCheck.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def details(self):
        """Gets the details of this InflightCheck.  # noqa: E501

        Details regarding the state of the inflight check.  # noqa: E501

        :return: The details of this InflightCheck.  # noqa: E501
        :rtype: object
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this InflightCheck.

        Details regarding the state of the inflight check.  # noqa: E501

        :param details: The details of this InflightCheck.  # noqa: E501
        :type: object
        """

        self._details = details

    @property
    def ended_at(self):
        """Gets the ended_at of this InflightCheck.  # noqa: E501

        The time the check finished running.  # noqa: E501

        :return: The ended_at of this InflightCheck.  # noqa: E501
        :rtype: datetime
        """
        return self._ended_at

    @ended_at.setter
    def ended_at(self, ended_at):
        """Sets the ended_at of this InflightCheck.

        The time the check finished running.  # noqa: E501

        :param ended_at: The ended_at of this InflightCheck.  # noqa: E501
        :type: datetime
        """

        self._ended_at = ended_at

    @property
    def name(self):
        """Gets the name of this InflightCheck.  # noqa: E501

        The name of the inflight check.  # noqa: E501

        :return: The name of this InflightCheck.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InflightCheck.

        The name of the inflight check.  # noqa: E501

        :param name: The name of this InflightCheck.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def restarts(self):
        """Gets the restarts of this InflightCheck.  # noqa: E501

        The number of times the inflight check restarted.  # noqa: E501

        :return: The restarts of this InflightCheck.  # noqa: E501
        :rtype: int
        """
        return self._restarts

    @restarts.setter
    def restarts(self, restarts):
        """Sets the restarts of this InflightCheck.

        The number of times the inflight check restarted.  # noqa: E501

        :param restarts: The restarts of this InflightCheck.  # noqa: E501
        :type: int
        """

        self._restarts = restarts

    @property
    def started_at(self):
        """Gets the started_at of this InflightCheck.  # noqa: E501

        The time the check started running.  # noqa: E501

        :return: The started_at of this InflightCheck.  # noqa: E501
        :rtype: datetime
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this InflightCheck.

        The time the check started running.  # noqa: E501

        :param started_at: The started_at of this InflightCheck.  # noqa: E501
        :type: datetime
        """

        self._started_at = started_at

    @property
    def state(self):
        """Gets the state of this InflightCheck.  # noqa: E501


        :return: The state of this InflightCheck.  # noqa: E501
        :rtype: InflightCheckState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this InflightCheck.


        :param state: The state of this InflightCheck.  # noqa: E501
        :type: InflightCheckState
        """

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InflightCheck):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InflightCheck):
            return True

        return self.to_dict() != other.to_dict()
