# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ocm_client.configuration import Configuration


class NetworkVerification(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cloud_provider_data': 'CloudProviderData',
        'cluster_id': 'str',
        'items': 'list[SubnetNetworkVerification]',
        'platform': 'Platform',
        'total': 'int'
    }

    attribute_map = {
        'cloud_provider_data': 'cloud_provider_data',
        'cluster_id': 'cluster_id',
        'items': 'items',
        'platform': 'platform',
        'total': 'total'
    }

    def __init__(self, cloud_provider_data=None, cluster_id=None, items=None, platform=None, total=None, local_vars_configuration=None):  # noqa: E501
        """NetworkVerification - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._cloud_provider_data = None
        self._cluster_id = None
        self._items = None
        self._platform = None
        self._total = None
        self.discriminator = None

        if cloud_provider_data is not None:
            self.cloud_provider_data = cloud_provider_data
        if cluster_id is not None:
            self.cluster_id = cluster_id
        if items is not None:
            self.items = items
        if platform is not None:
            self.platform = platform
        if total is not None:
            self.total = total

    @property
    def cloud_provider_data(self):
        """Gets the cloud_provider_data of this NetworkVerification.  # noqa: E501


        :return: The cloud_provider_data of this NetworkVerification.  # noqa: E501
        :rtype: CloudProviderData
        """
        return self._cloud_provider_data

    @cloud_provider_data.setter
    def cloud_provider_data(self, cloud_provider_data):
        """Sets the cloud_provider_data of this NetworkVerification.


        :param cloud_provider_data: The cloud_provider_data of this NetworkVerification.  # noqa: E501
        :type: CloudProviderData
        """

        self._cloud_provider_data = cloud_provider_data

    @property
    def cluster_id(self):
        """Gets the cluster_id of this NetworkVerification.  # noqa: E501

        Cluster ID needed to execute the network verification.  # noqa: E501

        :return: The cluster_id of this NetworkVerification.  # noqa: E501
        :rtype: str
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this NetworkVerification.

        Cluster ID needed to execute the network verification.  # noqa: E501

        :param cluster_id: The cluster_id of this NetworkVerification.  # noqa: E501
        :type: str
        """

        self._cluster_id = cluster_id

    @property
    def items(self):
        """Gets the items of this NetworkVerification.  # noqa: E501

        Details about each subnet network verification.  # noqa: E501

        :return: The items of this NetworkVerification.  # noqa: E501
        :rtype: list[SubnetNetworkVerification]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this NetworkVerification.

        Details about each subnet network verification.  # noqa: E501

        :param items: The items of this NetworkVerification.  # noqa: E501
        :type: list[SubnetNetworkVerification]
        """

        self._items = items

    @property
    def platform(self):
        """Gets the platform of this NetworkVerification.  # noqa: E501


        :return: The platform of this NetworkVerification.  # noqa: E501
        :rtype: Platform
        """
        return self._platform

    @platform.setter
    def platform(self, platform):
        """Sets the platform of this NetworkVerification.


        :param platform: The platform of this NetworkVerification.  # noqa: E501
        :type: Platform
        """

        self._platform = platform

    @property
    def total(self):
        """Gets the total of this NetworkVerification.  # noqa: E501

        Amount of network verifier executions started.  # noqa: E501

        :return: The total of this NetworkVerification.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this NetworkVerification.

        Amount of network verifier executions started.  # noqa: E501

        :param total: The total of this NetworkVerification.  # noqa: E501
        :type: int
        """

        self._total = total

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NetworkVerification):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NetworkVerification):
            return True

        return self.to_dict() != other.to_dict()
