# coding: utf-8

"""
    clusters_mgmt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: ocm-feedback@redhat.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ocm_client.configuration import Configuration


class OpenIDClaims(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'email': 'list[str]',
        'groups': 'list[str]',
        'name': 'list[str]',
        'preferred_username': 'list[str]'
    }

    attribute_map = {
        'email': 'email',
        'groups': 'groups',
        'name': 'name',
        'preferred_username': 'preferred_username'
    }

    def __init__(self, email=None, groups=None, name=None, preferred_username=None, local_vars_configuration=None):  # noqa: E501
        """OpenIDClaims - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._email = None
        self._groups = None
        self._name = None
        self._preferred_username = None
        self.discriminator = None

        if email is not None:
            self.email = email
        if groups is not None:
            self.groups = groups
        if name is not None:
            self.name = name
        if preferred_username is not None:
            self.preferred_username = preferred_username

    @property
    def email(self):
        """Gets the email of this OpenIDClaims.  # noqa: E501

        List of claims to use as the mail address.  # noqa: E501

        :return: The email of this OpenIDClaims.  # noqa: E501
        :rtype: list[str]
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this OpenIDClaims.

        List of claims to use as the mail address.  # noqa: E501

        :param email: The email of this OpenIDClaims.  # noqa: E501
        :type: list[str]
        """

        self._email = email

    @property
    def groups(self):
        """Gets the groups of this OpenIDClaims.  # noqa: E501

        List of claims to use as the group name.  # noqa: E501

        :return: The groups of this OpenIDClaims.  # noqa: E501
        :rtype: list[str]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this OpenIDClaims.

        List of claims to use as the group name.  # noqa: E501

        :param groups: The groups of this OpenIDClaims.  # noqa: E501
        :type: list[str]
        """

        self._groups = groups

    @property
    def name(self):
        """Gets the name of this OpenIDClaims.  # noqa: E501

        List of claims to use as the display name.  # noqa: E501

        :return: The name of this OpenIDClaims.  # noqa: E501
        :rtype: list[str]
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OpenIDClaims.

        List of claims to use as the display name.  # noqa: E501

        :param name: The name of this OpenIDClaims.  # noqa: E501
        :type: list[str]
        """

        self._name = name

    @property
    def preferred_username(self):
        """Gets the preferred_username of this OpenIDClaims.  # noqa: E501

        List of claims to use as the preferred user name when provisioning a user.  # noqa: E501

        :return: The preferred_username of this OpenIDClaims.  # noqa: E501
        :rtype: list[str]
        """
        return self._preferred_username

    @preferred_username.setter
    def preferred_username(self, preferred_username):
        """Sets the preferred_username of this OpenIDClaims.

        List of claims to use as the preferred user name when provisioning a user.  # noqa: E501

        :param preferred_username: The preferred_username of this OpenIDClaims.  # noqa: E501
        :type: list[str]
        """

        self._preferred_username = preferred_username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OpenIDClaims):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OpenIDClaims):
            return True

        return self.to_dict() != other.to_dict()
